### ISSUE TITLE
Ability to use the query string to specify input

### ISSUE THREAD

**Issue by Godsmith** [ivan7237d/jscalc#34] opened 2015-08-18 15:00 UTC
I.e. the ability to go to https://jscalc.io/calc/A0io7a1dmV9tu5o3?calculation=kppsToGbps&kpps=1000&packet_size=500 and have the specified fields filled in.

(Thank you for the great app, I just stumbled upon it today!)

**Comment by ivan7237d** [comment] 2015-08-18 17:55
Yes, this would be nice and pretty easy to implement, but with a URL fragment rather than query string. A duplicate of #14

**Closed by ivan7237d** 2015-08-18 17:55 UTC
