### ISSUE TITLE
Number missing from input and output pulldowns

### ISSUE THREAD

**Issue by richtwales** [ivan7237d/jscalc#33] opened 2015-07-23 20:37 UTC
Demo video shows general number format option in pulldown for inputs and outputs. Doesn't work. Only output is table. I'm running in chrome on Windows 7. Did this get taken away?

**Comment by ivan7237d** [comment] 2015-08-11 19:37
Sorry for slow response. I couldn't reproduce this, here's for example the outputs that I see:

<img width="456" alt="screen shot 2015-08-11 at 1 23 10 pm" src="https://cloud.githubusercontent.com/assets/9092817/9204851/e17dd518-402c-11e5-8009-3345dd0aef8f.png">

Could you pls post a screenshot?

**Comment by Godsmith** [comment] 2015-08-18 12:16
Hi, I have the same problem. The Value option is missing from both input and output for me.

![image](https://cloud.githubusercontent.com/assets/6632699/9329630/795d7bdc-45b3-11e5-91a6-3e304366d691.png)
![image](https://cloud.githubusercontent.com/assets/6632699/9329645/a8256e3e-45b3-11e5-9ecb-2b8061219e32.png)

**Comment by Godsmith** [comment] 2015-08-18 12:18
Oh wait, it's a duplicate of #30. Reducing the width of the window makes it pop up again. I only figured that out by reading the other bug report though, so a general user would probably never figure that out.

**Comment by ivan7237d** [comment] 2015-08-18 17:52
Thanks, didn't realize it myself. Working on it, should fix soon.

**Closed** 2015-08-18 17:53 UTC
Labels: resolution: duplicate
